mysite/autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

mysite/cats/urls.py
from django.urls import path

from . import views
app_name = 'cats'

urlpatterns = [
    path('', views.CatList.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedList.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path
from django.views.static import serve
from django.conf.urls import url


from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('',TemplateView.as_view(template_name='home/main.html')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('hello/',include('hello.urls')),
    path('admin/', admin.site.urls),
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/cats/models.py
from django.db import models

# Create your models here.
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(max_length=200,validators=[MinLengthValidator(2,'Breed must be greater than one character.')])

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(max_length=200, validators=[MinLengthValidator(2,"Nickname must be greater than 1 character.")])
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/cats/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Cat, Breed
# Create your views here.
class CatList(LoginRequiredMixin, ListView):
    model = Cat
    def get_context_data(self, **kwargs):
        BreedNum = Breed.objects.all().count()
        context = super().get_context_data(**kwargs)
        context['BreedNum']=BreedNum
        return context

class BreedList(LoginRequiredMixin, ListView):
    model = Breed

class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedCreate(LoginRequiredMixin, CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedUpdate(LoginRequiredMixin, UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

class BreedDelete(LoginRequiredMixin, DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:all')

mysite/cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed : {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'autos:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form method='POST'>
      {% csrf_token %}
      <table>
          {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
      <input type="submit" onclick="window.location='{% url 'autos:all' %}'; return;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/breed_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}

<h2>Breeds List</h2>
<ul>
    {% for breed in breed_list %}
        <li> {{breed.name}} (<a href="{% url 'cats:breed_update' breed.id %}">Update</a> | <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a>) </li>
    {% endfor %}
</ul>
<div><a href="{% url 'cats:breed_create' %}">Add a breed</a></div>

<div><a href="{% url 'cats:all' %}">Back to cats</a></div>

{% endblock %}

mysite/cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Cat</h1>

<p>Are you sure you want to delete the cat: {{ cat }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form method='POST'>
      {% csrf_token %}
      <table>
          {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
      <input type="submit" onclick="window.location='{% url 'autos:all' %}'; return;" value="Cancel">
  </form>
{% endblock %}

mysite/cats/templates/cats/cat_list.html
{% extends 'base_bootstrap.html' %}

{% block content %}

<h2>Cats List</h2>
<ul>
    {% for cat in cat_list %}
        <li> {{cat.nickname}} ({{cat.breed}}) (<a href="{% url 'cats:cat_update' cat.id %}">Update</a> | <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a>) </li>
    {% endfor %}
</ul>
<div><a href="{% url 'cats:cat_create' %}">Add a cat</a></div>

<div><a href="{% url 'cats:breed_list' %}">View breeds</a> ({{BreedNum}}) | <a href="{% url 'cats:breed_create' %}">Add a breed</a></div>

{% endblock %}